---
# roles/ansible-role-packages/tasks/os-pkgmanager.yml

- name: Detect rpm-ostree system
  ansible.builtin.stat:
    path: /run/ostree-booted
  register: _packages_ostree_booted

- name: Include Debian native package management
  ansible.builtin.include_tasks:
    file: nativepkgs-Debian.yml
  when: ansible_facts.os_family == 'Debian'

- name: Include RedHat native package management
  ansible.builtin.include_tasks:
    file: nativepkgs-RedHat.yml
  when: ansible_facts.os_family == 'RedHat'

- name: Include rpm-ostree native package management
  ansible.builtin.include_tasks:
    file: nativepkgs-RpmOsTree.yml
  when: _packages_ostree_booted.stat.exists
